clientes/urls.py
# -*- encoding: utf-8 -*-
"""clientes URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import include, url
from django.contrib import admin
from core import urls as core_urls

urlpatterns = [
    url(r'^', include(core_urls)),
    url(r'^admin/', include(admin.site.urls)),
]

core/urls.py
# -*- encoding: utf-8 -*-
from django.conf.urls import include, url
from tastypie.api import Api
from . import views
from api import *

v1_api = Api(api_name='v1')
v1_api.register(ClienteResource())
v1_api.register(TelefoneResource())
v1_api.register(ProjetoResource())
v1_api.register(HorasTrabalhoResource())
v1_api.register(InvoiceResource())

urlpatterns = [
    url(r'^$', views.index),
    url(r'^login/$', views.login),
    url(r'^cliente/', include([
        url(r'^$', views.cliente_lista),
        url(r'^novo/$', views.cliente_novo),
        url(r'^editar/(?P<slug>[\w-]+)$', views.cliente_editar),
        url(r'^salvar/$', views.cliente_salvar, {'id':None}),
        url(r'^salvar/(?P<id>\w+)/$', views.cliente_salvar),
    ])),

    url(r'^api/', include(v1_api.urls)),

    url(r'^forms$', views.forms),
    url(r'^tables$', views.tables),
]

core/models.py
# -*- encoding: utf-8 -*-

from django.db import models, IntegrityError, transaction
from django.utils.text import slugify
from datetime import datetime

import re

TIPO_TELEFONE = (
    ('celular',"Móvel Pessoal"),
    ('celular-profissional',"Móvel Profissional"),
    ('fixo',"Fixo"),
    ('fixo-residencial',"Fixo Residencial"),
    ('fixo-comercial',"Fixo Comercial"),
)

OPERADORAS = (
        ('claro',"Claro"),
        ('vivo',"Vivo"),
        ('tim',"Tim"),
        ('oi',"Oi"),
        ('nextel',"Nextel"),
        ('ctbc',"CTBC Telecom"),
        ('porto',"Porto Seguro Conecta"),
        ('sercomtel',"Sercomtel"),
)

DDD_BRASIL = tuple( [(str(x),str(x)) for x in range(11,100)] )

FORMA_PAGTO = (
        ("deposito","Depósito em CC"),
        ("paypal","Paypal"),
        ("pagseguro","Pagseguro"),
        ("maos","Em mãos"),
        ("bitcoins","Bitcoins"),
        ("free","Não cobrado"),
        ("troca","Troca"),
)

class BaseModel(models.Model):
    data_criacao = models.DateTimeField(auto_now_add=True)
    ultima_alteracao = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True # <--- denotes our model as abstract

class SlugModel(BaseModel):
    """Esta classe é utilizada para Models que necessitam do campo slug"""

    class Meta:
        abstract = True # <--- denotes our model as abstract

    slugfield = "name"

    def save(self, *args, **kwargs):
        """Auto-populate an empty slug field from the MyModel name and
        if it conflicts with an existing slug then append a number and try
        saving again.
        """
        if not self.slug:
            self.slug = slugify(getattr(self, self.slugfield))  # Where self.name is the field used for 'pre-populate from'

        while True:
            try:
                res = super(SlugModel, self).save(*args, **kwargs)
                return res
            except IntegrityError:
                match_obj = re.match(r'^(.*)-(\d+)$', self.slug)
                if match_obj:
                    next_int = int(match_obj.group(2)) + 1
                    self.slug = match_obj.group(1) + '-' + str(next_int)
                else:
                    self.slug += '-2'
            else:
                break

class Telefone(BaseModel):
    """Dados telefonicos do cliente"""
    numero = models.CharField(max_length=50)
    ddd = models.CharField(max_length=5, choices=DDD_BRASIL)
    tipo = models.CharField(max_length=35, choices=TIPO_TELEFONE)
    operadora = models.CharField(max_length=50, choices=OPERADORAS)
    whatsapp = models.BooleanField(default=False)


class Cliente(SlugModel):
    slugfield = "nome"

    """Os clientes"""
    nome = models.CharField(max_length=255)
    nome_contato = models.CharField(max_length=255)
    telefone = models.ForeignKey(Telefone, null=True, blank=True)
    email = models.EmailField()
    skype = models.CharField(max_length=1255, blank=True)
    facebook = models.CharField(max_length=1255, blank=True)
    twitter = models.CharField(max_length=1255, blank=True)
    linkedin = models.CharField(max_length=1255, blank=True)
    google_plus = models.CharField(max_length=1255, blank=True)
    slug = models.SlugField(unique=True)


class Projeto(BaseModel):
    """Projeto"""
    nome = models.CharField(max_length=255)
    descricao = models.TextField(max_length=2000, null=True, blank=True)
    valor_hora = models.PositiveSmallIntegerField()
    cliente = models.ForeignKey(Cliente)
    slug = models.SlugField(unique=True)


class HorasTrabalho(BaseModel):
    """Hora de trabalho feita"""
    projeto = models.ForeignKey(Projeto)
    quantidade = models.PositiveSmallIntegerField()
    valor_promocional = models.PositiveSmallIntegerField()
    resumo = models.CharField(max_length=800)


class DadosPagto(BaseModel):
    """Dados informativos da conta ou forma de pagto"""
    descricao = models.TextField(max_length=4000)
    forma_pagto = models.CharField(max_length=100, choices=FORMA_PAGTO)


class Invoice(BaseModel):
    """Invoices gerados e enviados aos clientes"""
    cliente = models.ForeignKey(Cliente)
    numero = models.PositiveIntegerField()
    horas = models.ManyToManyField(HorasTrabalho)
    email_alternativo = models.EmailField()
    enviado = models.BooleanField()
    forma_pagto = models.CharField(max_length=100, choices=FORMA_PAGTO)
    slug = models.SlugField(unique=True)

    def get_full_name(self):
        return self.cliente.nome + "{:04d}".format(self.numero)

core/forms.py
# -*- encoding: utf-8 -*-

from models import *
from django.forms import ModelForm, modelformset_factory, inlineformset_factory

class TelefoneForm(ModelForm):
    class Meta:
        model = Telefone
        fields = ['ddd', 'numero', 'tipo', 'operadora']

class ClienteForm(ModelForm):
    class Meta:
        model = Cliente
        fields = ['nome', 'nome_contato', 'telefone', 'email', 'skype', 'facebook', 'twitter', 'linkedin', 'google_plus']

    def save(self):
        instance = super(ClienteForm, self).save(commit=False)
        instance.slug = slugify(instance.nome)
        instance.save()

        return instance

class ProjetoForm(ModelForm):
    class Meta:
        model = Projeto
        fields = ['nome','descricao','valor_hora', 'cliente', 'slug']

    def save(self):
        instance = super(ProjetoForm, self).save(commit=False)
        instance.slug = slugify(instance.nome)
        instance.save()

        return instance


class HorasTrabalhoForm(ModelForm):
    class Meta:
        model = HorasTrabalho
        fields = ['projeto', 'quantidade', 'valor_promocional', 'resumo']

class DadosPagtoForm(ModelForm):
    class Meta:
        model = DadosPagto
        fields = ['descricao','forma_pagto']

class InvoiceForm(ModelForm):
    class Meta:
        model = Invoice
        fields = ['cliente', 'numero','horas','email_alternativo','enviado','forma_pagto','slug']

    def save(self):
        instance = super(InvoiceForm, self).save(commit=False)
        instance.slug = slugify(instance.get_full_name)
        instance.save()

        return instance

core/views.py
# -*- encoding: utf-8 -*-
from django.shortcuts import render, render_to_response, get_object_or_404
from django.template import RequestContext
from django.http import Http404
from forms import *

# Create your views here.
def index(request):
    return render(request, "index.html")

def login(request):
    return render(request, "login.html")

def forms(request):
    return render(request, "forms.html")

def tables(request):
    return render(request, "tables.html")

#============== CLIENTE ====================
def cliente_lista(request):
    clis = Cliente.objects.all()
    variables = RequestContext(request, {
        'clientes': clis
    })
    return render_to_response('cliente/list.html', variables)

def cliente_salvar(request, id=None):
    import pdb; pdb.set_trace()
    if id:
        cli = get_object_or_404(Cliente, id=id)
        clienteform = ClienteForm(request.POST, instance=cli)
        telefoneform = TelefoneForm(request.POST, instance=cli.telefone)
    else:
        clienteform = ClienteForm(request.POST)
        telefoneform = TelefoneForm(request.POST)

    newcli = clienteform.save()
    newtelefone = telefoneform.save()
    newcli.telefone = newtelefone
    newcli.save()

    return redirect('cliente_editar', slug=newcli.slug)

def cliente_editar(request, slug):
    cli = get_object_or_404(Cliente, slug=slug)
    if cli:
        clienteform = ClienteForm(instance=cli)
        telefoneform = TelefoneForm(instance=cli.telefone)
        variables = RequestContext(request, {
            'form': clienteform,
            'telefoneform': telefoneform,
            'cliente': cli,
        })
        return render_to_response('cliente/novo.html', variables)
    else:
        raise Http404("Cliente não existe")

def cliente_novo(request):
    clienteform = ClienteForm()
    telefoneform = TelefoneForm()
    variables = RequestContext(request, {
        'form': clienteform,
        'telefoneform': telefoneform,
    })
    return render_to_response('cliente/novo.html', variables)
    # return render(request, "tables.html")

core/templates/cliente/list.html
{%extends 'base.html'%}
{% load staticfiles %}

{%block js%}
    <!-- DataTables JavaScript -->
    <script src="{% static "bower_components/datatables/media/js/jquery.dataTables.min.js" %}"></script>
    <script src="{% static "bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js" %}"></script>

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
    $(document).ready(function() {
        $('#dataTables-example').DataTable({
                responsive: true
        });
    });
    </script>
{%endblock%}

{%block content%}
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Tables</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="dataTable_wrapper">
                        <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                            <thead>
                                <tr>
                                    <th>Rendering engine</th>
                                    <th>Browser</th>
                                    <th>Platform(s)</th>
                                    <th>Engine version</th>
                                    <th>CSS grade</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr class="odd gradeX">
                                    <td>Trident</td>
                                    <td>Internet Explorer 4.0</td>
                                    <td>Win 95+</td>
                                    <td class="center">4</td>
                                    <td class="center">X</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
{%endblock%}

core/templates/cliente/novo.html
{%extends 'base.html'%}
{% load bootstrap3 %}

{%block content%}

        {# Display django.contrib.messages as Bootstrap alerts #}
        {% bootstrap_messages %}

        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Novo cliente</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <div class="row">
                <div class="col-lg-10">
                    <form action="/cliente/salvar/" method="post" class="form" role="form">
                        {% csrf_token %}

                        {% for f in form %}
                            {%if f.name == 'telefone'%}
                            <div class="form-group">
                                <label class="control-label" for="id_nome_contato">Telefone</label><span class="text-info">(ddd, número, tipo, operadora móvel)</span>
                                <div id="telefone" class="form-inline">
                                {% bootstrap_form telefoneform layout='inline' %}
                                <button type="button" class="btn btn-default btn-sm">{% bootstrap_icon "plus" %}</button>
                                </div>
                            </div>
                            {%else%}
                                {% bootstrap_field f%}
                            {%endif%}

                        {% endfor %}
                        {% buttons submit='Salvar' reset="Cancelar" %}{% endbuttons %}
                    </form>
                </div>
            </div>
        </div>
        <!-- /#page-wrapper -->

{%endblock%}